name: M3U8 Checker

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Repositoriesi klonla
        uses: actions/checkout@v3

      - name: Python 3.10 kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Gerekli paketleri yükle
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Python scripti çalıştır
        run: |
          python m3u8_checker.py
